### ISSUE TITLE
Time scale on workbench don't match up with CVS output

### ISSUE THREAD

**Issue by JessCappadonna** [QutBioacoustics/baw-audio-tools#9]
Today, Michael and I tried to use a CSV document of annotations to find where EEB calls were annotated by myself last week, as there is no easy way to search for them in the website without manually re-reviewing spectrograms, or to know what data has been reviewed already on the website. I found that it was quite difficult to use the CSV files to do this, with CVS headings being quite confusing (e.g.  event_start_time_utc and  event_start_datetime_utc appear to be identical), and wondered if there is a headings glossary that users can also download. One thing that might also help marry up the web and CSV times would be to include the hours in the annotation times (hh:mm:ss format rather than mm:ss).  @atruskie @cofiem @jwim1

**Comment by atruskie** [comment]
This issue has been opened in the wrong repository. This is a public repo for programs that cut and convert segments of audio.

Other points:
 - Searching for annotations? The annotation library is being remade to deal with this
 - Navigating to them? See the `listen_url` column
 - We currently have no concept of reviewing or verification of annotations. This should be discussed as a separately.
 - RE `event_start_time_utc` and `event_start_datetime_utc`: Excel has difficulty reading dates and times in one column. Therefore we have to split them out into separate columns. The split format is annoying for other users so we keep all columns. Open the CSV in notepad++ and you can verify the differences yourself.
 - The point about hh:mm:ss - full and exact datetimes are included in the files. Excel does not format them properly.
 - Mark and I are automatically tagged in these issues. Jason does not need to be unless there is some architectural issue to discuss.
 - Issues are tracking system for bugs/features/work items. Support is still best sourced in an email/chat format.
